demo_dbt:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: localhost
      port: 1433
      database: dbt_db_test
      schema: dbo
      user: sa
      password: DJrobot9810@